language: python

python:
  - "3.6"
  - "3.8"
git:
  depth: 10

notifications:
  email: false

services:
  - docker

install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh && /bin/bash $HOME/miniconda.sh -b -p $HOME/miniconda && . miniconda/bin/activate
  - conda update -n base -c defaults conda
  - conda create --name travis -y

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - conda activate travis
  - conda install -c conda-forge pyfmi pandas numpy matplotlib requests -y
  
script:
  - (cd testing && make test_all)

