language: python

git:
  depth: 10

notifications:
  email: false

services:
  - docker

install:
  - pip install --upgrade pip
  - pip install pandas numpy matplotlib requests pathlib requests_toolbelt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

jobs:
  include:
  - python: 3.9
    script: cd testing && make test_all
