dist: bionic

language: python

python:
  - "3.6"
  - "3.8"
git:
  depth: 10

notifications:
  email: false

services:
  - docker

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pandas numpy matplotlib requests
  - conda activate test-environment
  - conda install -c conda-forge pyfmi -y

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  
script:
  - (cd testing && make test_all)

