language: python

python:
  - "3.6"
  - "3.8"
git:
  depth: 10

notifications:
  email: false

services:
  - docker

install:
  - pip install --upgrade pip
  - pip install pandas numpy matplotlib requests

before_script:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh && /bin/bash $HOME/miniconda.sh -b -p $HOME/miniconda && . miniconda/bin/activate && conda update -n base -c defaults conda && conda create --name boptest -y && conda activate boptest && conda install -c conda-forge pyfmi -y
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  
script:
  - (cd testing && make test_all)

